name: Update config

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - main

jobs:
  Update-config:
    runs-on: ubuntu-latest
    steps:
      - name: 'clone repo'
        uses: actions/checkout@v3.3.0
      - name: Update config
        run: python update_config.py
