name: Update config

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - main

jobs:
  Update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: 'clone repo'
        uses: actions/checkout@v2
      - name: Update config
        run: |
          python update_config.py
          git config --global user.email "actions@github.com"  # 设置提交者的邮箱
          git config --global user.name "GitHub Actions"         # 设置提交者的名称
          git add .
          git commit -m "$(date '+%Y.%m.%d %H:%M:%S') Update config" 
          git push origin main

          
