name: Update config

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - main

jobs:
  Update-config:
    runs-on: ubuntu-latest
    steps:
      - name: 'clone repo'
        uses: actions/checkout@v2
      - name: Update config
        env:
          ACCESS_TOKEN: ${{ secrets.A1 }}
        run: |
          python update_config.py
          git config --global user.email "1462749078@qq.com"  # 设置提交者的邮箱
          git config --global user.name "yangyucacaa"         # 设置提交者的名称
          git add /api/v1passport/comm/config
          git commit -m "Update net1data"
          #git push
          git push https://${ACCESS_TOKEN}@github.com/yangyucacaa/netVPN1.git
